import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import useRecorder from "../lib/hooks/useRecorder";
import RecorderFooter from "../components/recorderFooter/RecorderFooter";
import usePlayer from "../lib/hooks/usePlayer";
import Cursor from "../components/cursor/Cursor";
import CodeEditor from "../components/codeEditor/CodeEditorModule";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [code, setCode] = useState("// Write your C code here");
  const {
    recordings,
    recorderElementRef,
    isRecording,
    isPlayerVisible,
    onRecordingStop,
    onRecordingStart,
    recordedTime,
    recorderEndTime,
    recorderStartTime,
    recordedAudio,
  } = useRecorder();

  const { isPlaying, setIsPlaying, cursorRef, progress } = usePlayer(
    recordings,
    recorderStartTime,
    recorderEndTime,
    recordedAudio
  );

  const handleUpload = () => {
    // Implement upload functionality here
    console.log("Upload the recorded video");
  };

  return (
    <div className="code-editor" ref={recorderElementRef}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CodeEditor code={code} setCode={setCode} />
      <Cursor cursorRef={cursorRef} />
      <RecorderFooter
        isRecording={isRecording}
        isPlaying={isPlaying}
        setIsPlaying={setIsPlaying}
        isPlayerVisible={isPlayerVisible}
        onStart={onRecordingStart}
        onStop={onRecordingStop}
        recordedTime={recordedTime}
        progress={progress}
        onUpload={handleUpload}
      />
    </div>
  );
}
